# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            devinl.im
tagline:          Devin Lim
description:      'Linux enthusiast<br>ğŸ‡®ğŸ‡©â¡ï¸ğŸ‡²ğŸ‡¾â¡ï¸ğŸ‡¦ğŸ‡ºâ¡ï¸ğŸ‡ºğŸ‡¸<br>Previously<br><a href="https://amazon.care">@Amazon</a> & <a href="https://polyverse.com/">@Polyverse</a>'
url:              https://devinl.im
baseurl:          /

author:
  name:           'Devin Lim'
  url:            https://www.linkedin.com/in/ayydavay/
  email:          devin@devinl.im

paginate:         5

github:
  repo:           https://github.com/poole/hyde

plugins: [jekyll-paginate, jekyll-gist, jekyll-seo-tag]
